location /lit/ {
	set $btcpay_route_upstream lnd_lit;
	rewrite ^/lit/(.*)$ /$1 break;
	proxy_pass https://$btcpay_route_upstream:8443;
	proxy_redirect ~^https://lnd_lit:8443/?(.*)$ /lit/$1;
}

# LND's wallet unlocker and state methods are not protected by macaroons. Return
# 500 to mimic ChangePassword after a wallet is open, and avoid logging bot traffic.
location ~* ^/lnrpc\.(WalletUnlocker/(GenSeed|InitWallet|UnlockWallet|ChangePassword)|State/(GetState|SubscribeState))$ {
	access_log off;
	return 500;
}

location ~* ^/(ln|loop|pool|lit)rpc\. {
	set $btcpay_route_upstream lnd_lit;
	proxy_pass https://$btcpay_route_upstream:8443;
	proxy_redirect ~^https://lnd_lit:8443(/.*)$ $1;
}
